### ISSUE TITLE
Problem rendering figure in Lee 2018 paper from Arxiv

### ISSUE THREAD

**Issue by gpdf** [howardisaacson/Intro-to-Astro2024#3]
On Macs, the one figure in the Lee 2018 paper (Fig. 1, on p. 6) does not seem to render properly, at least not in Preview or Safari.

Downloading the source from Arxiv, from https://arxiv.org/src/1804.08907 , provides a zip file which includes the file `foo-eps-converted-to.pdf` , which is apparently a PDF version of the EPS original, `foo.eps`, which is what is referenced in the LaTeX source.

Renamed to show its relationship to the paper, it's here: 
[Lee-2018-Exoplanets-Fig1.pdf](https://github.com/user-attachments/files/16120759/Lee-2018-Exoplanets-Fig1.pdf)

It would probably be useful to include the figure in the instructions for Week 1, if others are also having this problem.

**Comment by gpdf** [comment]
@chetanchawla @fdai-planet Just making sure this was on your radar

**Comment by chetanchawla** [comment]
Thanks for highlighting this @gpdf !
I Will put a note on the Week 1 README to capture this.
